task:
  name: SwerveCS
  physics_engine: ${..physics_engine}
  env:
    numEnvs: 36
    envSpacing: 20
    resetDist: 3.0
    clipObservations: 1.0
    clipActions: 1.0
    controlFrequencyInv: 12
    control:
      stiffness: 85.0
      damping: 2.0
      actionScale: 13.5
    episodeLength_s: 15
  sim:
    dt: 0.01
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    add_ground_plane: true
    add_distant_light: true
    use_flatcache: true
    enable_scene_query_support: false
    default_physics_material:
      static_friction: 1.0
      dynamic_friction: 1.0
      restitution: 0.0
    physx:
      worker_thread_count: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${eq:${....sim_device},"gpu"}
      solver_position_iteration_count: 4
      solver_velocity_iteration_count: 4
      contact_offset: 0.02
      rest_offset: 0.001
      bounce_threshold_velocity: 0.2
      friction_offset_threshold: 0.04
      friction_correlation_distance: 0.025
      enable_sleeping: true
      enable_stabilization: true
      max_depenetration_velocity: 100.0
      gpu_max_rigid_contact_count: 524288
      gpu_max_rigid_patch_count: 163840
      gpu_found_lost_pairs_capacity: 4194304
      gpu_found_lost_aggregate_pairs_capacity: 33554432
      gpu_total_aggregate_pairs_capacity: 4194304
      gpu_max_soft_body_contacts: 1048576
      gpu_max_particle_contacts: 1048576
      gpu_heap_capacity: 134217728
      gpu_temp_buffer_capacity: 33554432
      gpu_max_num_partitions: 8
    SwerveCS:
      override_usd_defaults: false
      fixed_base: false
      enable_self_collisions: false
      enable_gyroscopic_forces: true
      solver_velocity_iteration_count: 8
      sleep_threshold: 0.005
      stabilization_threshold: 0.001
      density: -1
      max_depenetration_velocity: 100.0
      contact_offset: 0.02
      rest_offset: 0.001
train:
  params:
    seed: ${...seed}
    algo:
      name: a2c_continuous
    model:
      name: continuous_a2c_logstd
    network:
      name: actor_critic
      separate: false
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: 0
          fixed_sigma: true
      mlp:
        units:
        - 256
        - 128
        - 64
        activation: elu
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:SwerveCS,${....experiment}}
      full_experiment_name: ${.name}
      device: ${....rl_device}
      device_name: ${....rl_device}
      env_name: rlgpu
      ppo: true
      mixed_precision: false
      normalize_input: true
      normalize_value: true
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 0.1
      normalize_advantage: true
      gamma: 0.99
      tau: 0.95
      learning_rate: 0.0003
      lr_schedule: adaptive
      kl_threshold: 0.008
      score_to_win: 20000
      max_epochs: 10000
      save_best_after: 50
      save_frequency: 25
      grad_norm: 1.0
      entropy_coef: 0.0
      truncate_grads: true
      e_clip: 0.2
      horizon_length: 10
      minibatch_size: 360
      mini_epochs: 8
      critic_coef: 4
      clip_value: true
      seq_len: 4
      bounds_loss_coef: 0.0001
task_name: ${task.name}
experiment: ''
num_envs: ''
seed: 42
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: gpu
sim_device: gpu
device_id: 0
rl_device: cuda:0
num_threads: 4
solver_type: 1
test: false
checkpoint: ''
headless: false
wandb_activate: false
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: swervesim
